CREATE SCHEMA "spend_lens";

CREATE TABLE "spend_lens"."users" (
                                      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "username" varchar UNIQUE NOT NULL,
                                      "first_name" varchar NOT NULL,
                                      "last_name" varchar NOT NULL,
                                      "email" varchar,
                                      "contact_number" varchar,
                                      "role_type_code" varchar NOT NULL,
                                      "created_by" integer NOT NULL,
                                      "created_date" timestamptz NOT NULL DEFAULT 'now()',
                                      "updated_by" integer,
                                      "updated_date" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "spend_lens"."role_types" (
                                           "code" varchar PRIMARY KEY,
                                           "name" varchar NOT NULL
);

CREATE TABLE "spend_lens"."cash_flow_types" (
                                                "code" varchar PRIMARY KEY,
                                                "name" varchar NOT NULL
);

CREATE TABLE "spend_lens"."cash_flows" (
                                           "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           "date" date NOT NULL,
                                           "name" varchar NOT NULL,
                                           "cash_flow_type_code" varchar NOT NULL,
                                           "amount" numeric(14,2) NOT NULL,
                                           "user_id" integer NOT NULL,
                                           "is_active" boolean NOT NULL DEFAULT true,
                                           "created_by" integer NOT NULL,
                                           "created_at" timestamptz NOT NULL DEFAULT 'now()',
                                           "updated_by" integer,
                                           "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "spend_lens"."banks" (
                                      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "name" varchar NOT NULL
);

CREATE TABLE "spend_lens"."asset_types" (
                                            "code" varchar PRIMARY KEY,
                                            "name" varchar NOT NULL
);

CREATE TABLE "spend_lens"."assets" (
                                       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "date" date NOT NULL,
                                       "asset_type_code" varchar NOT NULL,
                                       "bank_id" integer,
                                       "amount" numeric(14,2) NOT NULL,
                                       "user_id" integer NOT NULL,
                                       "is_active" boolean NOT NULL DEFAULT true,
                                       "created_by" integer NOT NULL,
                                       "created_at" timestamptz NOT NULL DEFAULT 'now()',
                                       "updated_by" integer,
                                       "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "spend_lens"."expense_types" (
                                              "code" varchar PRIMARY KEY,
                                              "name" varchar NOT NULL
);

CREATE TABLE "spend_lens"."expense_categories" (
                                                   "code" varchar PRIMARY KEY,
                                                   "name" varchar NOT NULL
);

CREATE TABLE "spend_lens"."payment_types" (
                                              "code" varchar PRIMARY KEY,
                                              "name" varchar NOT NULL
);

CREATE TABLE "spend_lens"."expenses" (
                                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "name" varchar NOT NULL,
                                         "date" date NOT NULL,
                                         "expense_type_code" varchar NOT NULL,
                                         "expense_category_code" varchar NOT NULL,
                                         "payment_type_code" varchar NOT NULL,
                                         "amount" numeric(14,2) NOT NULL,
                                         "user_id" integer NOT NULL,
                                         "is_active" boolean NOT NULL DEFAULT true,
                                         "created_by" integer NOT NULL,
                                         "created_at" timestamptz NOT NULL DEFAULT 'now()',
                                         "updated_by" integer,
                                         "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "spend_lens"."time_deposits" (
                                              "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              "bank_id" integer NOT NULL,
                                              "maturity_date" date NOT NULL,
                                              "principal_amount" numeric(14,2) NOT NULL,
                                              "user_id" integer NOT NULL,
                                              "is_active" boolean NOT NULL DEFAULT true,
                                              "created_by" integer NOT NULL,
                                              "created_at" timestamptz NOT NULL DEFAULT 'now()',
                                              "updated_by" integer,
                                              "updated_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE INDEX "idx_cash_flows_user_date" ON "spend_lens"."cash_flows" ("user_id", "date");

CREATE INDEX "idx_assets_user_date" ON "spend_lens"."assets" ("user_id", "date");

CREATE INDEX "idx_expenses_user_date" ON "spend_lens"."expenses" ("user_id", "date");

CREATE INDEX "idx_time_deposits_user_is_active" ON "spend_lens"."time_deposits" ("user_id", "is_active");

COMMENT ON COLUMN "spend_lens"."cash_flows"."amount" IS 'CHECK (amount >= 0)';

COMMENT ON COLUMN "spend_lens"."assets"."amount" IS 'CHECK (amount >= 0)';

COMMENT ON COLUMN "spend_lens"."expenses"."amount" IS 'CHECK (amount >= 0)';

COMMENT ON COLUMN "spend_lens"."time_deposits"."principal_amount" IS 'CHECK (principal_amount >= 0)';

ALTER TABLE "spend_lens"."users" ADD FOREIGN KEY ("role_type_code") REFERENCES "spend_lens"."role_types" ("code");

ALTER TABLE "spend_lens"."users" ADD FOREIGN KEY ("created_by") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."users" ADD FOREIGN KEY ("updated_by") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."cash_flows" ADD FOREIGN KEY ("cash_flow_type_code") REFERENCES "spend_lens"."cash_flow_types" ("code");

ALTER TABLE "spend_lens"."cash_flows" ADD FOREIGN KEY ("user_id") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."cash_flows" ADD FOREIGN KEY ("created_by") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."cash_flows" ADD FOREIGN KEY ("updated_by") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."assets" ADD FOREIGN KEY ("asset_type_code") REFERENCES "spend_lens"."asset_types" ("code");

ALTER TABLE "spend_lens"."assets" ADD FOREIGN KEY ("bank_id") REFERENCES "spend_lens"."banks" ("id");

ALTER TABLE "spend_lens"."assets" ADD FOREIGN KEY ("user_id") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."assets" ADD FOREIGN KEY ("created_by") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."assets" ADD FOREIGN KEY ("updated_by") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."expenses" ADD FOREIGN KEY ("expense_type_code") REFERENCES "spend_lens"."expense_types" ("code");

ALTER TABLE "spend_lens"."expenses" ADD FOREIGN KEY ("expense_category_code") REFERENCES "spend_lens"."expense_categories" ("code");

ALTER TABLE "spend_lens"."expenses" ADD FOREIGN KEY ("payment_type_code") REFERENCES "spend_lens"."payment_types" ("code");

ALTER TABLE "spend_lens"."expenses" ADD FOREIGN KEY ("user_id") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."expenses" ADD FOREIGN KEY ("created_by") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."expenses" ADD FOREIGN KEY ("updated_by") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."time_deposits" ADD FOREIGN KEY ("bank_id") REFERENCES "spend_lens"."banks" ("id");

ALTER TABLE "spend_lens"."time_deposits" ADD FOREIGN KEY ("user_id") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."time_deposits" ADD FOREIGN KEY ("created_by") REFERENCES "spend_lens"."users" ("id");

ALTER TABLE "spend_lens"."time_deposits" ADD FOREIGN KEY ("updated_by") REFERENCES "spend_lens"."users" ("id");
